### ISSUE TITLE
circular_slider requires SDK version >=2.12.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by sbois** [matthewfx/sleek_circular_slider#87]
Hi 
when I add the dependance in the YAML file and make a "flutter pub get" I always have this message 
```
The current Dart SDK version is 2.9.1.

Because circular_slider requires SDK version >=2.12.0 <3.0.0, version solving failed.
Running "flutter pub get" in circular_slider...
pub get failed (1; Because circular_slider requires SDK version >=2.12.0 <3.0.0, version solving failed.)

```
here is my YAML file : 

```
name: circular_slider
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sleek_circular_slider:
    path: ../
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 
```

Can anyone help me please ?
